services:
  mihomo:
    image: sqkam/mihomo
    container_name: mihomo
    network_mode: "host"
    restart: always
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
    volumes:
      - /root/.config/mihomo:/root/.config/mihomo

