mixed-port: 7890
external-controller: 0.0.0.0:9090
external-ui: ui
mode: rule
allow-lan: true
log-level: debug
secret: ''
sniffer:
  enable: true
  sniffing:
    - tls
    - http

keep-alive-interval: 10
dns:
  enable: false
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 1.1.1.1
tun:
  enable: false
  stack: gvisor

tcp-concurrent: true

experimental:
  quic-go-disable-gso: true
  quic-go-disable-ecn: true
  dialer-ip4p-convert: true
